### PR TITLE
simple update

### PR DESCRIPTION
**Pull request by PowaBanga**
updated just by rename version number and sha...

### CODE REVIEW

**Comment by asbachb** [comment]
@PowaBanga would you like to adopt the arch package? I'm not using arch anymore tbh.

**Comment by PowaBanga** [comment]
@asbachb yes, i want to adopt this package.. Thank you very much.

**Comment by asbachb** [comment]
@PowaBanga what's your archlinux name? I can add you as co-maintainer and the disown the package. We don't need to delete it.

**Comment by asbachb** [comment]
I added you as a maintainer in archlinux. But keep in mind to generate the `.SRCINFO` in case you do any further update.

**Pull request closed without merging**
